### ISSUE TITLE
Wrong multi monitor capturing on Ubuntu 20.04 / Debian Buster 10.9 

### ISSUE THREAD

**Issue by patrick-blom** [sblantipodi/firefly_luciferin#44] opened 2021-05-12 15:43 UTC
## Firefly Luciferin version  
1.11.6

## Glow Worm Luciferin version  
4.8.5 Full Version

## Describe the bug
First of all, sorry for not using 100% of the issue template. The problems are difficult to describe and I think that way is the best solution.

### The Bug(s)
If you are using the multi display (dual or triple mode) under Linux the screen capturing does not work as expected. The display capturing is not exactly bound to configured displays and on top the effects are mirrored on each display.

The setup is as follows. I have 1 laptop with 2 external displays. All 3 displays are in use. Mon 3 and Mon 2 are prepared with leds. Mon 1 has no leds. 

![Image of setup](https://github.com/patrick-blom/luciferin_debug_information/blob/cc1d5fb0eb35d59fcb09fa42a999dc5d677ddfb8/global_setup/setup_mon.png?raw=true)

Luciferin is configured to the dual monitor mode and both instances have their own esp8266 and mqtt topic.

![config mode debian](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/settings_mode.png?raw=true)
![config device debian](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/settings_device.png?raw=true)
![config mqtt](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/settings_mqtt.png?raw=true)

![mqtt screen](https://github.com/patrick-blom/luciferin_debug_information/blob/master/ubuntu/mqtt_explorere.png?raw=true)

### The binding problem
During the capturing, Mon 1 is included to the process but not bound to any instance(display). If I move a white window to the right side of Mon1, the leds on the right side of Mon 3 and Mon 2 will be on. I would expect that Mon 1 is complete ignored by the capturing process because it's not bound to any Luciferin instance.

![binding problem](https://github.com/patrick-blom/luciferin_debug_information/blob/master/global_setup/setup_capture.png?raw=true)

### The duplication problem
All movements of the leds are duplicated to both displays(Mon 2 & Mon 3). If I drag a window to the left upper corner of Mon 3, the leds on Mon 2 will light up as well. That happens in all directions. I would expect that only the leds on Mon 3 would light up.

## Logs and configuration
I can reproduce both problems on Ubuntu 20.04 and Debian Buster 10.9. To provide as much information as possible, I add the configurations and log files of Luciferin for both systems. They can be found in this repository:

https://github.com/patrick-blom/luciferin_debug_information

## Sumup
I hope you can reproduce the issues with my given information, if not, plz feel free to ping me. 

Cheers Patrick

**Comment by sblantipodi** [comment] 2021-05-13 10:13
this is the best description of an issue that I have seen on GitHub since ever. wow.
I will look into in, hope to give you an answer soon and possibly a fix in the same time.

Thank you Patrick.

**Comment by sblantipodi** [comment] 2021-05-13 14:15
@patrick-blom can you uninstall Firefly Luciferin and try this ALPHA version please?
In this URL, you can find and download the ALPHA artifacts.
https://github.com/sblantipodi/firefly_luciferin/actions/runs/839056957

Does it fix "the duplication problem"?

**Comment by patrick-blom** [comment] 2021-05-13 18:08
@sblantipodi yes, in the ALPHA that looks good.

Now the behavior is as follows: 
The only monitor which leds are active, is atm Mon2. If I drag a window to the right side of Mon 1, the leds on the right side of Mon 2 are active, If I drag a window to the left side of Mon 3, the leds on the left side of Mon 2 are on. Same with up and down. 

It seems, that now the capturing effects all monitors but only use Mon 2 (the center) as output, but I could not reproduce any duplication. No matter which direction, the output is not duplicated and fixed on Mon 2.

So yes, the duplication problem seems to be fixed. 🤓 Nice work 👍

**Comment by sblantipodi** [comment] 2021-05-13 21:04
@patrick-blom on Discord you wrote me this: "btw: I disabled the lid for testing purposes, that worked like a charm  :smile:" 

can you elaborate this please? what happened when you disabled the lid using the current stable Firefly Luciferin?

**Comment by patrick-blom** [comment] 2021-05-13 22:05
@sblantipodi After a detailed check I think I have to revert that post 🙈 😕The stable version also has the duplication bug when the lid is closed. 

The Alpha behaves nearly the same when the lid is closed but with a different output. If the lid is closed Mon 3 becomes Mon 1 and Mon 2 stays the same. 

If that happens, Mon 1 will be used as Output and the leds of the right side will turn on if I drag a Windows to the right side of Mon 2

**Comment by sblantipodi** [comment] 2021-05-14 09:31
I'm not able to reproduce it so I need to ask you some more questions...
what happen if you drag a windows on the side of Mon2 using the ALPHA version?

Does the led behind the mon2 turn on correctly?

if you open a console and write this command:
gst-launch-1.0 ximagesrc **display-name=:3** ! videoscale ! videoconvert ! autovideosink

a window should open and capture what is shown on screen 3, can you confirm it? if no, what do you see?

can you do the same with the same command changing the display name?
gst-launch-1.0 ximagesrc **display-name=:2** ! videoscale ! videoconvert ! autovideosink
and
gst-launch-1.0 ximagesrc **display-name=:1** ! videoscale ! videoconvert ! autovideosink

thank you!!!!

**Comment by patrick-blom** [comment] 2021-05-14 10:02
No problem! Ask as many questions as needed. 

"
what happen if you drag a windows on the side of Mon2 using the ALPHA version?
Does the led behind the mon2 turn on correctly?
"
No, it does not work correctly. The leds on the side of Mon 2 (left & right) only light up if I drag a window to the sides of Mon 1 and Mon 3. 

The output of the commands are as follows (I translated it using google translate because my OS runs on the german language):

```
~/Downloads » gst-launch-1.0 ximagesrc display-name=:2 ! videoscale ! videoconvert ! autovideosink  
Line is set to PAUSED ...
ERROR: Line does not want to be paused.
ERROR: From element / GstPipeline: pipeline0 / GstXImageSrc: ximagesrc0: Could not open X display for reading
Additional error diagnostic information:
gstximagesrc.c (160): gst_ximage_src_open_display (): / GstPipeline: pipeline0 / GstXImageSrc: ximagesrc0:
NULL returned from getting xcontext
Line is set to ZERO ...
Line is emptied ...
```

```
~/Downloads » gst-launch-1.0 ximagesrc display-name=:3 ! videoscale ! videoconvert ! autovideosink     
Line is set to PAUSED ...
ERROR: Line does not want to be paused.
ERROR: From element / GstPipeline: pipeline0 / GstXImageSrc: ximagesrc0: Could not open X display for reading
Additional error diagnostic information:
gstximagesrc.c (160): gst_ximage_src_open_display (): / GstPipeline: pipeline0 / GstXImageSrc: ximagesrc0:
NULL returned from getting xcontext
Line is set to ZERO ...
Line is emptied ...
```

If I run the command with `display-name=:1` I will get a new window with this content: 
![display-name=:1](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/gst-launch-1.0-ximagesrc.png?raw=true)

**Comment by patrick-blom** [comment] 2021-05-14 11:25
@sblantipodi 
I played around with that command you wrote me and I was able to capture all my diplays separately by providing the start / end positions.

In my setup ponit 0.0 is the upper left corner of Mon 3 so I could capture each display using the following commands:

- Mon1: gst-launch-1.0 ximagesrc display-name=:1.0 startx=3840 ! videoscale ! videoconvert ! autovideosink  
- Mon2: gst-launch-1.0 ximagesrc display-name=:1.0 startx=1920 endx=3840 ! videoscale ! videoconvert ! autovideosink
- Mon3: gst-launch-1.0 ximagesrc display-name=:1.0 endx=1920 ! videoscale ! videoconvert ! autovideosink

All displays are on 1920x1080

Hope that information is useful. 

Cheers Patrick

**Comment by sblantipodi** [comment] 2021-05-14 16:29
@patrick-blom 
you are not a java dev but from your answers I can understand that you are a dev 😄 

can you tell me if this command shows only the contents on display 1 please?
Mon1: gst-launch-1.0 ximagesrc display-name=:1.0 startx=3840 ! videoscale ! videoconvert ! autovideosink

this shows only contents for monitor 2?
Mon2: gst-launch-1.0 ximagesrc display-name=:1.0 startx=1920 endx=3840 ! videoscale ! videoconvert ! autovideosink

and this monitor 3 only?
Mon2: gst-launch-1.0 ximagesrc display-name=:1.0 startx=1920 endx=3840 ! videoscale ! videoconvert ! autovideosink

**Comment by patrick-blom** [comment] 2021-05-14 17:13
@sblantipodi 😄 Thx

Regarding your questions:

> can you tell me if this command shows only the contents on display 1 please?
> Mon1: gst-launch-1.0 ximagesrc display-name=:1.0 startx=3840 ! videoscale ! videoconvert ! autovideosink

Yes it does 

> this shows only contents for monitor 2?
> Mon2: gst-launch-1.0 ximagesrc display-name=:1.0 startx=1920 endx=3840 ! videoscale ! videoconvert ! autovideosink

Yes it does 

> and this monitor 3 only?
> Mon3: gst-launch-1.0 ximagesrc display-name=:1.0 startx=1920 endx=3840 ! videoscale ! videoconvert ! autovideosink

No it doesn't because its the same command as for monitor 2 ^^

This command will only show the contents of monitor 3 
Mon3: gst-launch-1.0 ximagesrc display-name=:1.0 startx=0 endx=1920 ! videoscale ! videoconvert ! autovideosink

**Comment by sblantipodi** [comment] 2021-05-14 21:15
@patrick-blom 
if you want to try another apha, here it is:
https://github.com/sblantipodi/firefly_luciferin/actions/runs/843386229

thank you again!

**Comment by sblantipodi** [comment] 2021-05-14 21:37
please note that on Linux Luciferin capture the screen only if something is moving on the screen.
just in case you see 0FPS on a screen that have nothing moving on on it.

**Comment by patrick-blom** [comment] 2021-05-15 06:08
@sblantipodi Funny thing regarding the fps, even if there is no movement on the monitors, its even producing 1.2-1.7 fps ^^ 

But back top topic. First off all this alpha works much better than the version before, thx a lot 🤓👍

The verison, in detail, behaves likes this:
- All movements of Mon 3 are fine. There is no unexpected behavior. 
- The leds of Mon 2 are now more dim than the ones of Mon 3. You can reproduce that if you drag a windows slowly along the top of both mon's.( All instances at 100% brightness ) 
- The leds displays of mon 2 and mon 1 are still combinded, so the right leds of mon 2 will be on if I move a window to the right side of mon 1. Same for top and down movements.
- If I place a window between mon 1 and mon 2 (half of both) no leds will lite up.  I think that happens, because of ximagesrc thinks I'm in the middle of a screen. I would expect, that only the leds of the right side of mon 2 will be on.
- If I place a window between mon 2 and mon 3 only the leds of mon 3 (right side) will turn on not the leds of mon 2 (left side). 

Regarding the last point (mon2 & mon3), I dont know the behavior of the windows version, but I think that the current behavior is totally ok. Because I would expect that the whole background light has the same intensity over all leds / monitors. If both sides where on mon 3 (right side) and mon 2 (left side), it might be to bright because of double amount of the leds.

**Comment by sblantipodi** [comment] 2021-05-15 12:06
@patrick-blom 
1-2FPS is normal, the important thing is that the FPS increase if something is moving on the screen.

I'm sorry for the time you are wasting behind those trials and errors Patrick.
This should really fix it.
https://github.com/sblantipodi/firefly_luciferin/actions/runs/844831472

**Comment by patrick-blom** [comment] 2021-05-15 16:18
@sblantipodi That's absolutely no problem. I know how hard debugging is, and every minute that I can help you with testing the alpha is a minute that makes Luciferin a better application. So even if this problem is fixed, if you need someone to test a new feature under linux, besides your own tests, feel free to ping me 🤓

Back to the alpha, sry but nope 🙈: 
The behavior is nearly the same to the last version,  with slight differences. 
- The dim problem of mon 2 is still present also that it seems mon 1 and mon 2 are combined and seen as one big display.
- Mon 3 has recreated the duplication bug. But only for the left side. So if I drag a window to the left side the leds of mon 3 (left) and mon 2 (left) will turn on.
- The combination of mon 1 and mon 2. It seems that the virtual edge of the right side of mon 1 has moved into the left direction. In the last version I had to drag the window to the very outer edge of mon 1 to light up the right leds of mon 2. Now the lights will turn on earlier, I think a few hundred pixels. 

#### last version
![last version](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/last_version.png?raw=true)

#### current version
![current version](https://github.com/patrick-blom/luciferin_debug_information/blob/master/debian/current_version.png?raw=true)

**Comment by sblantipodi** [comment] 2021-05-16 19:29
I finally attached another monitor to my Linux box, and here it is.
https://github.com/sblantipodi/firefly_luciferin/actions/runs/847579949

**Comment by patrick-blom** [comment] 2021-05-17 15:14
@sblantipodi 
I just installed the latest alpha, and what should I say, it works perfectly 😍!

- no doublication 
- the binding of monitors works as expeteced
- all leds are at the same level of brightness

Thank you for all your effort and patience to fix this bug! Great Job 👍

**Comment by sblantipodi** [comment] 2021-05-17 15:42
@patrick-blom 
thank you for the best bug report I have seen and for helping me in fixing the problem.

This fix will be merged on the master branch in some days, once merged the issue will be closed automatically.

I hope to continue to see you around Patrick! 

Thanks,
Davide

**Closed** 2021-05-31 17:09 UTC
Labels: bug
